ViopOrtalamaHesaplama/Controllers/ContractAveragesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ViopOrtalama.Business.Abstract;
using ViopOrtalama.Entities.Enitities;
using ViopOrtalamaHesaplama.UI.Models.Contracts;

namespace ViopOrtalamaHesaplama.UI.Controllers
{
    [Authorize]

    public class ContractAveragesController : Controller
    {

        private readonly IGenericService<Contract> _contractService;
        private readonly UserManager<AppUser> _userManager;

        public ContractAveragesController(UserManager<AppUser> userManager, IGenericService<Contract> contractService)
        {
            _contractService = contractService;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> ContractAverageOpenOnes()
        {
            AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            List<Contract> contracts = _contractService.GetDefault(x => x.AppUser.Id == currentUser.Id)
              .GroupBy(x => new { x.Company, x.Expiry, x.Position })
              .Where(g => g.Count() > 0)
              .SelectMany(g => g)
               .OrderByDescending(c => c.CreateDate)
              .ToList();
            static ContractAvarageVM MapToAvarageVM(Contract contract)
            {
                return new ContractAvarageVM
                {
                    ContractID = contract.Id,
                    Company = contract.Company,
                    Expiry = contract.Expiry,
                    Position = contract.Position,
                    SelectedPosition = contract.Position,
                    Quantity = contract.Quantity,
                    Price = contract.Price,
                    
                };
            }

            List<ContractAvarageVM> contractAvarageVMs = contracts.Select(c => MapToAvarageVM(c)).ToList();
            return View(contractAvarageVMs);
        }


        [HttpGet]
        public async Task<IActionResult> ContractAverageOnExpiry()
        {
            AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            return View();
        }


        [HttpGet]
        public async Task<IActionResult> ContractAveragesCompany()
        {
            AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            // Kullanıcının işlemlerini al
            List<Contract> contracts = _contractService.GetDefault(x => x.AppUser.Id == currentUser.Id)
                .ToList();

            // Şirket, vade ve pozisyon özelliklerine göre gruplandır
            var groupedContracts = contracts.GroupBy(c => new
            {
                Company = c.Company.Value,
                Expiry = c.Expiry.Value,
                Position = c.Position
            });

            // Her grup için adet ve fiyat özelliklerini çarp ve ortalamayı hesapla
            List<CompanyAvarages> contractAvarageVMs = new List<CompanyAvarages>();
            foreach (var group in groupedContracts)
            {
                var totalQuantity = group.Sum(c => c.Quantity);
                var totalPrice = group.Sum(c => c.Quantity * c.Price);
                var companyAverages = new CompanyAvarages
                {
                    Company = group.Key.Company,
                    Expiry = group.Key.Expiry,
                    Position = group.Key.Position,
                    Quantity = totalQuantity,
                    Price = totalPrice,
                    ContactAverage = totalQuantity > 0 ? totalPrice / totalQuantity : 0
                };

                contractAvarageVMs.Add(companyAverages);
            }

            return View(contractAvarageVMs);
        }





    }
}

ViopOrtalamaHesaplama/Controllers/ContractController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using ViopOrtalama.Business.Abstract;
using ViopOrtalama.Entities.Enitities;
using ViopOrtalamaHesaplama.UI.FluentValidators.ContractValidations;
using ViopOrtalamaHesaplama.UI.Models.Contracts;
using ViopOrtalamaHesaplama.UI.Models.Users;

namespace ViopOrtalamaHesaplama.UI.Controllers
{
    [Authorize]

    public class ContractController : Controller
    {

        private readonly IGenericService<Contract> _contractService;
        private readonly UserManager<AppUser> _userManager;

        public ContractController(UserManager<AppUser> userManager, IGenericService<Contract> contractService)
        {
            _contractService = contractService;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> CreateContractCompany()
        {
            AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateContractCompany(CreateContractCompanyVM ccvm)
        {

            var validator = new CreateCompanyVMValidator();
            var validationResult = validator.Validate(ccvm);

            if (!validationResult.IsValid)
            {
                // Validation failed, return with errors
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }

                return View(ccvm);
            }
            
            AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            Contract contract = new Contract();

            contract.AppUser = currentUser;
            contract.Quantity = ccvm.Quantity;

            string priceString = ccvm.Price.Replace(',', '.'); // Virgül yerine nokta kullanımını desteklemek için
            contract.Price = decimal.Parse(priceString, CultureInfo.InvariantCulture);
            contract.Company = ccvm.Company;
            contract.Expiry = ccvm.Expiry;
            contract.Position = ccvm.SelectedPosition;
            contract.AppUser.Id = currentUser.Id;
             _contractService.Add(contract);
            return RedirectToAction("ContractAverageOpenOnes", "ContractAverages");
        
          

        }
       
        [HttpPost]
        public async Task<IActionResult> DeleteContract(int contractID)
        {
            Contract contract=_contractService.GetById(contractID);
            _contractService.Remove(contract);
            return RedirectToAction("ContractAverageOpenOnes", "ContractAverages");

        }

        /**/
        [HttpGet]
        public async Task<IActionResult> CreateContractCommodity()
        {
           


            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateContractCommodity(CreateContractCommodityVM cccvm)
        {
            AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            Contract contract = new Contract();

            contract.AppUser = currentUser;
            contract.Quantity = cccvm.Quantity;
            contract.Price = cccvm.Price;
            contract.Commodity = cccvm.Commodity;
            contract.Expiry = cccvm.Expiry;
            contract.Position = cccvm.SelectedPosition;
            contract.AppUser.Id = currentUser.Id;
            _contractService.Add(contract);



            return View();

        }
        /**/
        [HttpGet]
        public async Task<IActionResult> CreateContractCurrency()
        {
           


            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateContractCurrency(CreateContractCurrencyVM cccurencyvm)
        {
            AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            Contract contract = new Contract();

            contract.AppUser = currentUser;
            contract.Quantity = cccurencyvm.Quantity;
            contract.Price = cccurencyvm.Price;
            contract.Currency = cccurencyvm.Currency;
            contract.Expiry = cccurencyvm.Expiry;
            contract.Position = cccurencyvm.SelectedPosition;
            contract.AppUser.Id = currentUser.Id;
            _contractService.Add(contract);


            return View();

        }

        [HttpGet]
        public async Task<IActionResult> CreateContractAvarage()
        {
            


            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateContractAvarage(CreateContractAveragesVM vm)
        {
            AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            Contract contract = new Contract();

            contract.AppUser = currentUser;
            contract.Quantity = vm.Quantity;
            contract.Price = vm.Price;
            contract.Averages = vm.Averages;
            contract.Expiry = vm.Expiry;
            contract.Position = vm.SelectedPosition;
            contract.AppUser.Id = currentUser.Id;
            _contractService.Add(contract);



            return View();

        }

        //    public async Task<IActionResult> OpenContract()
        //    {
        //        AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

        //        return View();
        //    }
        //    public async Task<IActionResult> MyArticleListForEdit()//tüm Contratlarımı görüntülediğim sayfa
        //    {
        //        AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);//login olan kullanıcı(author)


        //        return View(articles);
        //    }
        //    public async Task<IActionResult> ArticleDetails(int id)//makale detaylarım
        //    {
        //        AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
        //        Article article = _articleService.GetById(id);
        //        if (currentUser.Id == article.AuthorId)
        //        {
        //            return View(article);

        //        }
        //        return RedirectToAction("MyArticleListForEdit");
        //    }
        //
    }
}

ViopOrtalamaHesaplama/Views/ContractAverages/ContractAverageOpenOnes.cshtml
@using ViopOrtalamaHesaplama.UI.Models.Contracts
@model List<ContractAvarageVM>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "";
}

<!DOCTYPE html>
<html>
<head>
    <title>Contracts List</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.min.css">
    <style>
        body {
            padding: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Contract List</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Şirket</th>
                    <th>Vade</th>
                    <th>Pozisyon</th>
                    <th>Adet</th>
                    <th>Fiyat</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var contract in Model)
                {
                    <tr>
                        
                        <td>@contract.Company</td>
                        <td>@contract.Expiry.Value.GetDisplayName()--@contract.Expiry.GetValue()</td>
                        <td>@contract.SelectedPosition</td>
                        <td>@contract.Quantity</td>
                        <td>@contract.Price.ToString("N2")</td>
                       
                        <td>
                            <form method="post" asp-controller="Contract" asp-action="DeleteContract">
                                <input type="hidden" name="contractID" value="@contract.ContractID" />
                                <button type="submit" class="btn btn-danger" onclick="return confirm('Bu kontratı silmek istediğinizden emin misiniz?')">Sil</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

ViopOrtalamaHesaplama/Views/ContractAverages/ContractAveragesCompany.cshtml
@using ViopOrtalamaHesaplama.UI.Models.Contracts
@model List<CompanyAvarages>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Company Averages";
}

<!DOCTYPE html>
<html>
<head>
    <title>Company Averages</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        .average-cell {
            text-align: right;
        }
    </style>
</head>
<body>
    <h1>Company Averages</h1>
    <table>
        <thead>
            <tr>
                <th>Şirket</th>
                <th>Vade</th>
                <th>Pozisyon</th>
                <th>Adet</th>
                               <th>Ortalama</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var contractAverage in Model)
            {
                <tr>
                    <td>@contractAverage.Company</td>
                    <td>@contractAverage.Expiry.GetDisplayName()-@contractAverage.Expiry.GetValue()</td>
                    <td>@contractAverage.Position</td>
                    <td>@contractAverage.Quantity</td>
                    <td class="average-cell">@contractAverage.ContactAverage.ToString("N4")</td>
                </tr>
            }
        </tbody>
    </table>
    
</body>
</html>