ViopOrtalamaHesaplama/Controllers/ContractAveragesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ViopOrtalama.Business.Abstract;
using ViopOrtalama.Entities.Enitities;
using ViopOrtalamaHesaplama.UI.Models.Contracts;

namespace ViopOrtalamaHesaplama.UI.Controllers
{
    [Authorize]

    public class ContractAveragesController : Controller
    {

        private readonly IGenericService<Contract> _contractService;
        private readonly UserManager<AppUser> _userManager;

        public ContractAveragesController(UserManager<AppUser> userManager, IGenericService<Contract> contractService)
        {
            _contractService = contractService;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> ContractAverageOpenOnes()
        {
            AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            List<Contract> contracts = _contractService.GetDefault(x => x.AppUser.Id == currentUser.Id)
              .GroupBy(x => new { x.Company, x.Expiry, x.Position })
              .Where(g => g.Count() > 0)
              .SelectMany(g => g)
               .OrderByDescending(c => c.CreateDate)
              .ToList();
            static ContractAvarageVM MapToAvarageVM(Contract contract)
            {
                return new ContractAvarageVM
                {
                    ContractID = contract.Id,
                    Company = contract.Company,
                    Expiry = contract.Expiry,
                    Position = contract.Position,
                    SelectedPosition = contract.Position,
                    Quantity = contract.Quantity,
                    Price = contract.Price,
                    
                };
            }

            List<ContractAvarageVM> contractAvarageVMs = contracts.Select(c => MapToAvarageVM(c)).ToList();
            return View(contractAvarageVMs);
        }


        [HttpGet]
        public async Task<IActionResult> ContractAverageOnExpiry()
        {
            AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            return View();
        }


        [HttpGet]
        public async Task<IActionResult> ContractAveragesCompany()
        {
            AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            // Kullanıcının işlemlerini al
            List<Contract> contracts = _contractService.GetDefault(x => x.AppUser.Id == currentUser.Id)
                .ToList();

            // Şirket, vade ve pozisyon özelliklerine göre gruplandır
            var groupedContracts = contracts.GroupBy(c => new
            {
                Company = c.Company.Value,
                Expiry = c.Expiry.Value,
                Position = c.Position
            });

            // Her grup için adet ve fiyat özelliklerini çarp ve ortalamayı hesapla
            List<CompanyAvarages> contractAvarageVMs = new List<CompanyAvarages>();
            foreach (var group in groupedContracts)
            {
                var totalQuantity = group.Sum(c => c.Quantity);
                var totalPrice = group.Sum(c => c.Quantity * c.Price);
                var companyAverages = new CompanyAvarages
                {
                    Company = group.Key.Company,
                    Expiry = group.Key.Expiry,
                    Position = group.Key.Position,
                    Quantity = totalQuantity,
                    Price = totalPrice,
                    ContactAverage = totalQuantity > 0 ? totalPrice / totalQuantity : 0
                };

                contractAvarageVMs.Add(companyAverages);
            }

            return View(contractAvarageVMs);
        }





    }
}

ViopOrtalamaHesaplama/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Web;
using ViopOrtalama.Entities.Enitities;
using ViopOrtalama.Repositories.Abstract;
using ViopOrtalamaHesaplama.UI.Models;
using ViopOrtalamaHesaplama.UI.Models.Users;

namespace ViopOrtalamaHesaplama.UI.Controllers
{
    public class LoginController : Controller
    {
       private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
     
        public LoginController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager )
        {
            _userManager = userManager;
           
            _signInManager = signInManager; 
        }
      
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginVM loginViewModel)
        {
            var email = loginViewModel.Email.Normalize().ToLower();
            var user = await _userManager.FindByEmailAsync(email);


            var result = await _signInManager.PasswordSignInAsync(user, loginViewModel.Password, true, false);
            if (result.Succeeded)
            {
                
               

                    return RedirectToAction("CreateContractCompany", "Contract");
                
                //else lütfen mail adresinizi onaylayın
            }
            //kullanıcı adı veya şifre hatalı
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> LoginOut()
        {
            AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            if (currentUser != null)
            {
                await _signInManager.SignOutAsync();
                return RedirectToAction("index", "Home");
            }
            else
            {
                return RedirectToAction("index", "Home");
            }
        }
    }
}

ViopOrtalamaHesaplama/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


using ViopOrtalama.Entities.Enitities;
using ViopOrtalamaHesaplama.UI.FluentValidators.RegisterValidation;
using ViopOrtalamaHesaplama.UI.Models.Contracts;
using ViopOrtalamaHesaplama.UI.Models.Users;

namespace ViopOrtalamaHesaplama.UI.Controllers
{
    public class RegisterController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        public RegisterController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Register()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserRegisterVM userRegisterVM)
        {
            if (!ModelState.IsValid)
            {
                return View(userRegisterVM);
            }

            Random random = new Random();
            int code = random.Next(100000, 1000000);

            AppUser appUser = new AppUser()
            {
                FirstName = userRegisterVM.FirstName,
                LastName = userRegisterVM.LastName,
                Email = userRegisterVM.Email,
                PhoneNumber = userRegisterVM.PhoneNumber,
                Job = userRegisterVM.Job,
                BirthDate = userRegisterVM.BirthDate,
                UserName = Guid.NewGuid().ToString(),
                ConfirmCode = code,
            };

            var result = await _userManager.CreateAsync(appUser, userRegisterVM.Password);

            if (result.Succeeded)
            {
                // Kullanıcı başarılı bir şekilde oluşturulduysa, başka bir işlem yapabilirsiniz.
                // Örneğin, bir onay e-postası gönderme işlemi gerçekleştirebilirsiniz.

                return RedirectToAction("Login", "Login"); // İşlem başarılıysa, "Home" controller'ının "Index" action'ına yönlendirme yapıyorum.
            }
            else
            {
                // Kullanıcı oluşturma işlemi başarısız olduysa, hata mesajlarını işleme alabilirsiniz.
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                return View(userRegisterVM); // Hataları göstermek için tekrar formu döndürüyorum.
            }
        }



    }
}

ViopOrtalamaHesaplama/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ViopOrtalamaHesaplama</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ViopOrtalamaHesaplama.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ViopOrtalamaHesaplama</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contract" asp-action="CreateContractCompany">Kontrat Aç</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ContractAverages" asp-action="ContractAverageOpenOnes">Kontrat işlemleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ContractAverages" asp-action="ContractAveragesCompany">Ortalamalar</a>
                        </li>
                        
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Register">Kayıt Ol</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Giriş Yap</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LoginOut">Çıkış Yap</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
           Kayıt olmadan işlem yapamazsınız
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>